id: ADD69B3AB
title: A Sādhana of Sitātapatrā
type: translation
pechas:
- I5445A705
- IA09E04E0
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 13:11:32.226552
  last_modified_at: 2023-01-04 13:11:32.226559
  collections:
  - Mipham Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I5445A705/5E91: 9EDE
  IA09E04E0/8498: 9EDE
